### ISSUE TITLE
problem loading cosmic data

### ISSUE THREAD

**Issue by vg0219** [pysat/pysat#333] opened 2019-12-18 14:15 UTC
I would like to plot cosmic data using pysat and I have done the following:

`import pysat
pysat.utils.set_data_dir(path='/home/myusername/COSTO/COSMIC/')
cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='atmprf')
cosmic.load(fname='2011.069/atmPrf_C001.2011.069.00.01.G05_2013.3520_nc')`

From this last command I get:
` File "<stdin>", line 1, in <module>
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pysat/_instrument.py", line 1371, in load
    self.data, meta = self._load_data(date=self.date, fid=self._fid)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pysat/_instrument.py", line 1053, in _load_data
    sat_id=self.sat_id, **self.kwargs)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pysat/instruments/cosmic_gps.py", line 166, in load
    output = pysat.DataFrame(load_files(fnames, tag=tag, sat_id=sat_id))
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pysat/instruments/cosmic_gps.py", line 251, in load_files
    new['profiles'] = pysat.DataFrame(loadedVars)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 317, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length `
  
However, it seems to be finding the files.
`cosmic.files.files`
I get
`0
2011-03-10 00:01:00.034320    2011.069/atmPrf_C001.2011.069.00.01.G05_2013.3...
2011-03-10 00:02:00.055040    2011.069/atmPrf_C005.2011.069.00.02.G23_2013.3...
2011-03-10 00:02:00.077920    2011.069/atmPrf_C001.2011.069.00.02.G14_2013.3...
2011-03-10 00:03:00.056199    2011.069/atmPrf_C005.2011.069.00.03.G27_2013.3...
2011-03-10 00:03:00.056440    2011.069/atmPrf_C001.2011.069.00.03.G30_2013.3...
2011-03-10 00:04:00.002599    2011.069/atmPrf_C005.2011.069.00.04.G31_2013.3...
2011-03-10 00:04:00.027960    2011.069/atmPrf_C002.2011.069.00.04.G18_2013.3...
2011-03-10 00:04:00.050080    2011.069/atmPrf_C005.2011.069.00.04.G09_2013.3...
2011-03-10 00:05:00.054919    2011.069/atmPrf_C002.2011.069.00.05.G04_2013.3...
2011-03-10 00:06:00.059040    2011.069/atmPrf_C006.2011.069.00.06.G23_2013.3...
2011-03-10 00:08:00.069839    2011.069/atmPrf_C002.2011.069.00.08.G31_2013.3...
2011-03-10 00:09:00.025600    2011.069/atmPrf_C001.2011.069.00.09.G17_2013.3...
2011-03-10 00:09:00.026639    2011.069/atmPrf_C005.2011.069.00.09.G20_2013.3...
2011-03-10 00:09:00.052999    2011.069/atmPrf_C002.2011.069.00.09.G15_2013.3...
2011-03-10 00:10:00.000000    2011.069/atmPrf_C006.2011.069.00.10.G13_2013.3...
2011-03-10 00:10:00.006200    2011.069/atmPrf_C006.2011.069.00.10.G20_2013.3...
2011-03-10 00:14:00.004760    2011.069/atmPrf_C001.2011.069.00.14.G31_2013.3...
2011-03-10 00:15:00.007800    2011.069/atmPrf_C005.2011.069.00.15.G32_2013.3...
2011-03-10 00:15:00.009399    2011.069/atmPrf_C005.2011.069.00.15.G30_2013.3...
2011-03-10 00:15:00.019959    2011.069/atmPrf_C002.2011.069.00.15.G13_2013.3...
2011-03-10 00:15:00.044760    2011.069/atmPrf_C002.2011.069.00.15.G27_2013.3...
2011-03-10 00:15:00.060440    2011.069/atmPrf_C002.2011.069.00.15.G23_2013.3...
2011-03-10 00:15:00.064840    2011.069/atmPrf_C001.2011.069.00.15.G27_2013.3...
2011-03-10 00:15:00.065600    2011.069/atmPrf_C002.2011.069.00.15.G21_2013.3...
2011-03-10 00:16:00.026119    2011.069/atmPrf_C001.2011.069.00.16.G26_2013.3...
2011-03-10 00:16:00.077760    2011.069/atmPrf_C002.2011.069.00.16.G09_2013.3...
2011-03-10 00:17:00.034480    2011.069/atmPrf_C006.2011.069.00.17.G17_2013.3...
2011-03-10 00:18:00.078840    2011.069/atmPrf_C005.2011.069.00.18.G05_2013.3...
2011-03-10 00:20:00.042840    2011.069/atmPrf_C001.2011.069.00.20.G15_2013.3...
2011-03-10 00:20:00.050560    2011.069/atmPrf_C005.2011.069.00.20.G12_2013.3...

2011-03-11 23:38:00.044000    2011.070/atmPrf_C001.2011.070.23.38.G12_2013.3...
2011-03-11 23:39:00.056600    2011.070/atmPrf_C001.2011.070.23.39.G04_2013.3...
2011-03-11 23:40:00.030280    2011.070/atmPrf_C005.2011.070.23.40.G03_2013.3...
2011-03-11 23:40:00.071399    2011.070/atmPrf_C005.2011.070.23.40.G06_2013.3...
2011-03-11 23:41:00.001799    2011.070/atmPrf_C002.2011.070.23.41.G12_2013.3...
2011-03-11 23:41:00.019879    2011.070/atmPrf_C002.2011.070.23.41.G11_2013.3...
2011-03-11 23:41:00.022480    2011.070/atmPrf_C002.2011.070.23.41.G16_2013.3...
2011-03-11 23:41:00.033799    2011.070/atmPrf_C004.2011.070.23.41.G25_2013.3...
2011-03-11 23:41:00.073199    2011.070/atmPrf_C001.2011.070.23.41.G19_2013.3...
2011-03-11 23:42:00.018080    2011.070/atmPrf_C004.2011.070.23.42.G19_2013.3...
2011-03-11 23:42:00.064359    2011.070/atmPrf_C004.2011.070.23.42.G31_2013.3...
2011-03-11 23:43:00.006279    2011.070/atmPrf_C001.2011.070.23.43.G18_2013.3...
2011-03-11 23:43:00.010279    2011.070/atmPrf_C002.2011.070.23.43.G07_2013.3...
2011-03-11 23:43:00.057760    2011.070/atmPrf_C001.2011.070.23.43.G11_2013.3...
2011-03-11 23:43:00.067360 `

**Comment by rstoneback** [comment] 2019-12-18 19:12
Thanks for the report. I can confirm the issue on my local machine. I hope to have some time later today to sort this out.

**Comment by rstoneback** [comment] 2019-12-18 19:52
After checking the atmPrf files the issue is driven by the fact that the profiles have variables with different lengths. I'll need to modify the load routine to group the profile variables by length.

**Comment by rstoneback** [comment] 2019-12-19 00:29
First draft support has been added and is in pull #334.

**Comment by rstoneback** [comment] 2019-12-19 19:15
I believe the work in the pull is complete. I've requested a review and we will merge the fixes into the develop branch soon. Please let us know if the fix does not work for you.

**Comment by jklenzing** [comment] 2019-12-27 19:12
Hi @vg0219, the fixes are merged into the develop branch.  Please let us know if you are still seeing an issue.

**Closed** 2020-01-08 14:31 UTC
Labels: bug
