### ISSUE TITLE
Testing instrument options

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#583] opened 2020-10-19 15:09 UTC
**Describe the bug**
Some instruments have options for preprocessing that are not being tested (e.g., pysatNASA)

**Expected behavior**
Complete testing coverage of instruments

**Suggested fix**
Add a dict of optional inputs for particular instruments?

**Comment by jklenzing** [comment] 2021-09-13 17:02
Thinking about implementation, we could either 
- Add kwarg-based tests in the core pysat routines to ensure that such instruments load in a generic way
- Add specific tests in the packages to ensure specific behaviour is maintained

I'm leaning toward the second.

**Comment by rstoneback** [comment] 2021-09-13 18:14
I missed this issue when I added #805. I found that adding tests within the specific package worked well. 

We could write a generalized test that engages instrument keywords but we wouldn't, in general, know how to test that the keyword worked as intended.  I think instrument specific tests are going to be needed no matter what so I lean towards the second option above.

**Comment by jklenzing** [comment] 2021-10-04 17:57
After looking at how to implement this downstream of #915, I'm leaning more strongly toward option 2 (deal with it in individual projects).

Adding and extracting kwarg dictionaries is straightforward for each test, but implementing through parametrize is not.  We would probably have to define a "queue" of options as part of each test, then loop through these under `InstLibTests.test_load`.    I'm worried this would be harder to trace back errors.

**Comment by jklenzing** [comment] 2021-10-04 21:33
Found an option to move forward: This requires generating 4 instrument lists rather than 3.  The fourth list can be the downloaded instruments + the instrument options with optional keywords.  Will put up a draft when I've verified against pysatNASA

**Comment by jklenzing** [comment] 2021-10-06 13:05
Closing with merge of #919

**Closed by jklenzing** 2021-10-06 13:05 UTC
Labels: testing
