### ISSUE TITLE
Load a day of data for Constellation with Instrument missing data

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#1031] opened 2022-08-04 22:12 UTC
**Describe the bug**
If not all of the instruments have data loading a Constellation object can error.

**To Reproduce**
```
# Instantiate constellation of COSMIC-2 IVMs
ids = [''.join(['e', str(i + 1)]) for i in range(6)]
const = [pysat.Instrument('cosmic2', 'ivm', inst_id=i, 
                          clean_level='none') for i in ids]
const = pysat.Constellation(instruments=const)

const.load(2020, 10)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [95], in <module>
----> 1 const.load(2020, 10)

File ~/Code/pysat/pysat/_constellation.py:752, in Constellation.load(self, *args, **kwargs)
    748 # If any data has been loaded, set time data and continue processing
    749 if not self.empty:
    750     # Set the year and doy attributes for the constellation and
    751     # instruments
--> 752     self.yr, self.doy = pysat.utils.time.getyrdoy(self.date)
    754     # Apply the Constellation-level custom functions
    755     pysat.Instrument.custom_apply_all(self)

File ~/Code/pysat/pysat/_constellation.py:587, in Constellation.date(self)
    583 @property
    584 def date(self):
    585     """Date for loaded data."""
--> 587     if len(self.index) > 0:
    588         return pysat.utils.time.filter_datetime_input(self.index[0])
    589     else:

File ~/Code/pysat/pysat/_constellation.py:620, in Constellation.index(self)
    616 @property
    617 def index(self):
    618     """Obtain time index of loaded data."""
--> 620     return self._index()

File ~/Code/pysat/pysat/_constellation.py:442, in Constellation._index(self)
    439 else:
    440     # Adjust the start and stop time as appropriate
    441     if self.common_index:
--> 442         if stime < inst.index[0]:
    443             stime = inst.index[0]
    444         if etime > inst.index[-1]:

File ~/opt/anaconda3/envs/jan2022/lib/python3.9/site-packages/pandas-1.4.0rc0-py3.9-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py:5013, in Index.__getitem__(self, key)
   5010 if is_integer(key) or is_float(key):
   5011     # GH#44051 exclude bool, which would return a 2d ndarray
   5012     key = com.cast_scalar_indexer(key, warn_float=True)
-> 5013     return getitem(key)
   5015 if isinstance(key, slice):
   5016     # This case is separated from the conditional above to avoid
   5017     # pessimization com.is_bool_indexer and ndim checks.
   5018     result = getitem(key)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Expected behavior**
Tolerant of Instruments with missing data.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Python 3.9
 - Other details about your setup that could be relevant

**Additional context**

**Comment by jklenzing** [comment] 2023-03-06 19:11
Duplicate of #798

**Closed by jklenzing** 2023-03-06 19:11 UTC
